version: '3'
services:
  preekrooster:
    build: .
    container_name: preekrooster_app
    volumes:
      - preekrooster:/app
    env_file: stack.env
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true

volumes:
  preekrooster: