version: '3'
services:
  preekrooster_script:
    build:
      context: /home/docker/containers/preekrooster_script
    container_name: preekrooster_script
    volumes:
      - /home/docker/containers/preekrooster_script:/app
    env_file: stack.env
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped