services:
  preekrooster-script:
    image: python:3.10-slim
    container_name: preekrooster-script
    volumes:
      - /home/docker/containers/preekrooster-script:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && python script.py"
    env_file:
      - stack.env